#!/usr/bin/env python3
import random

a = 0
b = 0
c = 0
d = 0
e = 0
x = 0

while x < 10000:
	a = random.randint(1, 500)
	b = random.randint(1, 500)
	c = random.randint(1, 10)
	d = a + b * c
	e += 1
	if d > x:
		x = d
		print(x)
	if e == 10000:
		print("Out of tries!")
		break
